package com.example.shirodemo.dao;

import com.example.shirodemo.entity.GenAdminRolePermission;
import com.example.shirodemo.entity.GenAdminRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenAdminRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    long countByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int insert(GenAdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(GenAdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermission selectOneByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermission selectOneByExampleSelective(@Param("example") GenAdminRolePermissionExample example, @Param("selective") GenAdminRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    List<GenAdminRolePermission> selectByExampleSelective(@Param("example") GenAdminRolePermissionExample example, @Param("selective") GenAdminRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    List<GenAdminRolePermission> selectByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermission selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") GenAdminRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenAdminRolePermission record, @Param("example") GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenAdminRolePermission record, @Param("example") GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenAdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenAdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}