# 数据库连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username: root
      password: root
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 6000
# mail
  mail:
    host: smtp.sina.com
    username: nvwuzaishuohuang@sina.com
    password: f726ab99e3651b23
# Redis
  redis:
    port: 6379
    host: 192.168.130.156
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5


# 手机验证码 key
PHONE_CODE_kEY: phoneCodess
# 短信
SING_NAME: 紫竹家电
TEMPLATE_CODE: SMS_183150143


